name: 'Dependency Review'
on: 
  pull_request:
    branches: [ master, main, demo ]
  push:
    branches: [ dev ]

permissions:
  contents: read
  pull-requests: write # so comments can be added on PRs

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Dependency Review (PR)
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4
        with:
          license-check: true
          vulnerability-check: true
          comment-summary-in-pr: always
          fail-on-severity: high
          # deny-licenses is deprecated
          allow-licenses: Apache-2.0, MIT, PostgreSQL, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD, 0BSD AND ISC AND MIT
          allow-dependencies-licenses: pkg:npm/%2540synerio/engage-core
          fail-on-scopes: runtime
          warn-only: true


      - name: Dependency Review (Push)
        if: github.event_name == 'push'
        uses: actions/dependency-review-action@v4
        with:
          license-check: true
          vulnerability-check: false
          fail-on-severity: high
          # deny-licenses is deprecated
          allow-licenses: Apache-2.0, MIT, PostgreSQL, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD, 0BSD AND ISC AND MIT
          allow-dependencies-licenses: pkg:npm/%2540synerio/engage-core
          fail-on-scopes: runtime
          warn-only: false
          base-ref: master
          head-ref: ${{ github.ref_name }}